import "dotenv/config";
import { GoogleGenerativeAI } from "@google/generative-ai";

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

export const sendMessage = async (req, res) => {
  try {
    const { message } = req.body;
    if (!message) {
      return res.status(400).json({ message: "Message is required" });
    }

    const prompt = `Bạn là một AI ChatBox chuyên trả lời những câu hỏi về Quan điểm cơ bản của chủ nghĩa Mác-Lênin về giai cấp công nhân và sứ mệnh lịch sử của giai cấp công nhân. Đây là tài liệu mà bạn sẽ dựa vào để trả lời câu hỏi:

1. Khái niệm và đặc điểm của giai cấp công nhân 
a) Khái niệm giai cấp công nhân
	C. Mác và Ph. Ăngghen đã sử dụng nhiều thuật ngữ khác nhau để chỉ giai cấp công nhân như giai cấp vô sản; giai cấp vô sản hiện đại; giai cấp công nhân hiện đại; giai cấp công nhân đại công nghiệp... Đó là những cụm từ đồng nghĩa để chỉ giai cấp công nhân - con đẻ của nền đại công nghiệp tư bản chủ nghĩa, giai cấp đại biểu cho lực lượng sản xuất tiên tiến, cho phương thức sản xuất hiện đại. Ngoài ra, các ông còn dùng những thuật ngữ có nội dung hẹp hơn để chỉ các loại công nhân trong các ngành sản xuất khác nhau, trong những giai đoạn phát triển khác nhau của công nghiệp như: công nhân khoáng sản, công nhân công trường thủ công, công nhân công xưởng, công nhân nông nghiệp...
	Dù diễn đạt bằng những thuật ngữ khác nhau, song giai cấp công nhân được các nhà kinh điển xác định theo hai phương diện cơ bản:
	- Về phương diện kinh tế – xã hội:
	Là sản phẩm và là chủ thể của nền sản xuất đại công nghiệp, giai cấp công nhân là những người lao động trực tiếp hay gián tiếp vận hành các công cụ sản xuất có tính chất công nghiệp ngày càng hiện đại và xã hội hóa cao. Họ lao động bằng phương thức công nghiệp ngày càng hiện đại với những đặc điểm nổi bật: sản xuất bằng máy móc, lao động có tính chất xã hội hóa, năng suất lao động cao và tạo ra những tiền đề của cải vật chất cho xã hội mới.
	Mô tả quá trình phát triển của giai cấp công nhân, C. Mác và Ph. Ăngghen chỉ rõ: “Trong công trường thủ công và trong nghề thủ công, người công nhân sử dụng công cụ của mình, còn trong công xưởng thì người công nhân phải phục vụ máy móc”. Theo C. Mác và Ph. Ăngghen, công nhân công nghiệp công xưởng là bộ phận tiêu biểu cho giai cấp công nhân hiện đại.
	Trong tác phẩm Tuyên ngôn của Đảng Cộng sản, các ông nhấn mạnh: “các giai cấp khác đều suy tàn và tiêu vong cùng với sự phát triển của đại công nghiệp, còn giai cấp vô sản lại là sản phẩm của bản thân nền đại công nghiệp” và “công nhân cũng là một phát minh của thời đại mới, giống như máy móc vậy... Công nhân Anh là đứa con đầu lòng của nền công nghiệp hiện đại”.
	- Về phương diện chính trị - xã hội:
	Từ lịch sử phát triển của chủ nghĩa tư bản, giai cấp công nhân còn là sản phẩm xã hội của quá trình phát triển tư bản chủ nghĩa, một xã hội có “điều kiện tồn tại dựa trên cơ sở chế độ làm thuê”. Trong quan hệ sản xuất tư bản chủ nghĩa, “giai cấp vô sản là giai cấp những công nhân làm thuê hiện đại, vì mất các tư liệu sản xuất của bản thân, nên buộc phải bán sức lao động của mình để sống”.
	C. Mác và Ph. Ăngghen chỉ rõ, đó là giai cấp của những người lao động không có sở hữu tư liệu sản xuất chủ yếu của xã hội. Họ phải bán sức lao động cho nhà tư bản và bị chủ tư bản bóc lột giá trị thặng dư. Đối diện với nhà tư bản, công nhân là những người lao động tự do, với nghĩa là tự do bán sức lao động của mình để kiếm sống. Chính điều này khiến cho giai cấp công nhân trở thành giai cấp đối kháng với giai cấp tư sản. “Những công nhân ấy, buộc phải tự bán mình để kiếm ăn từng bữa một, là một hàng hóa, tức là một món hàng đem bán như bất cứ món hàng nào khác, vì thế, họ phải chịu hết mọi sự may rủi của cạnh tranh, mọi sự lên xuống của thị trường với mức độ như nhau”
	Mâu thuẫn cơ bản của phương thức sản xuất tư bản chủ nghĩa là mâu thuẫn giữa lực lượng sản xuất xã hội hóa ngày càng rộng lớn với quan hệ sản xuất tư bản chủ nghĩa dựa trên chế độ tư hữu tư bản chủ nghĩa về tư liệu sản xuất. Mâu thuẫn cơ bản này thể hiện về mặt xã hội là mâu thuẫn về lợi ích giữa giai cấp công nhân và giai cấp tư sản. Lao động sống của công nhân là nguồn gốc của giá trị thặng dư và sự giàu có của giai cấp tư sản cũng chủ yếu nhờ vào việc bóc lột được ngày càng nhiều hơn giá trị thặng dư.
	Mâu thuẫn đó cho thấy tính chất đối kháng không thể điều hòa giữa giai cấp công nhân (giai cấp vô sản) với giai cấp tư sản trong phương thức sản xuất tư bản chủ nghĩa và trong chế độ tư bản chủ nghĩa.
	Từ phân tích trên, theo chủ nghĩa Mác - Lênin: Giai cấp công nhân là một tập đoàn xã hội, hình thành và phát triển cùng với quá trình phát triển của nền công nghiệp hiện đại; họ lao động bằng phương thức công nghiệp ngày càng hiện đại và gắn liền với quá trình sản xuất vật chất hiện đại, là đại biểu cho phương thức sản xuất mang tính xã hội hóa ngày càng cao. Họ là người làm thuê do không có tư liệu sản xuất, buộc phải bán sức lao động để sống và bị giai cấp tư sản bóc lột giá trị thặng dư; vì vậy lợi ích cơ bản của họ đối lập với lợi ích cơ bản của giai cấp tư sản. Đó là giai cấp có sứ mệnh phủ định chế độ tư bản chủ nghĩa, xây dựng thành công chủ nghĩa xã hội và chủ nghĩa cộng sản trên toàn thế giới.
	b) Đặc điểm của giai cấp công nhân
	Nghiên cứu giai cấp công nhân (giai cấp vô sản) từ phương diện kinh tế - xã hội và chính trị - xã hội trong chủ nghĩa tư bản, C. Mác và Ph. Ăngghen đã không những đưa lại quan niệm khoa học về giai cấp công nhân mà còn làm sáng tỏ những đặc điểm quan trọng của nó với tư cách là một giai cấp cách mạng có sứ mệnh lịch sử thế giới. Có thể khái quát những đặc điểm chủ yếu của giai cấp công nhân bao gồm:
	- Đặc điểm nổi bật của giai cấp công nhân là lao động bằng phương thức công nghiệp với đặc trưng công cụ lao động là máy móc, tạo ra năng suất lao động cao, quá trình lao động mang tính chất xã hội hóa.
	- Giai cấp công nhân là sản phẩm của bản thân nền đại công nghiệp, là chủ thể của quá trình sản xuất vật chất hiện đại. Do đó, giai cấp công nhân là đại biểu cho lực lượng sản xuất tiên tiến, cho phương thức sản xuất tiên tiến, quyết định sự tồn tại và phát triển của xã hội hiện đại.
	- Nền sản xuất đại công nghiệp và phương thức sản xuất tiên tiến đã rèn luyện cho giai cấp công nhân những phẩm chất đặc biệt về tính tổ chức, kỷ luật lao động, tinh thần hợp tác và tâm lý lao động công nghiệp. Đó là một giai cấp cách mạng và có tinh thần cách mạng triệt để.
	Những đặc điểm ấy chính là những phẩm chất cần thiết để giai cấp công nhân có vai trò lãnh đạo cách mạng.

2. Nội dung sứ mệnh lịch sử của giai cấp công nhân
	Nội dung sứ mệnh lịch sử của giai cấp công nhân chính là những nhiệm vụ mà giai cấp công nhân cần phải thực hiện với tư cách là giai cấp tiên phong, là lực lượng đi đầu trong cuộc cách mạng xác lập hình thái kinh tế - xã hội cộng sản chủ nghĩa.
	Theo chủ nghĩa Mác - Lênin, sứ mệnh lịch sử tổng quát của giai cấp công nhân là thông qua chính đảng tiền phong, giai cấp công nhân tổ chức, lãnh đạo nhân dân lao động đấu tranh xóa bỏ các chế độ người bóc lột người, xóa bỏ chủ nghĩa tư bản, giải phóng giai cấp công nhân, nhân dân lao động khỏi mọi sự áp bức, bóc lột, nghèo nàn, lạc hậu, xây dựng xã hội cộng sản chủ nghĩa văn minh.
	Nói về sứ mệnh lịch sử của giai cấp công nhân, C. Mác đã viết: “Thực hiện sự nghiệp giải phóng thế giới ấy, - đó là sứ mệnh lịch sử của giai cấp vô sản hiện đại”.
Sứ mệnh lịch sử của giai cấp công nhân thể hiện trên ba nội dung cơ bản:
	- Nội dung kinh tế:
	Là nhân tố hàng đầu của lực lượng sản xuất xã hội hóa cao, giai cấp công nhân cũng là đại biểu cho quan hệ sản xuất mới, sản xuất ra của cải vật chất ngày càng nhiều đáp ứng nhu cầu ngày càng tăng của con người và xã hội. Bằng cách đó, giai cấp công nhân tạo tiền đề vật chất - kỹ thuật cho sự ra đời của xã hội mới.
	Mặt khác, tính chất xã hội hóa cao của lực lượng sản xuất đòi hỏi một quan hệ sản xuất mới, phù hợp với chế độ công hữu các tư liệu sản xuất chủ yếu của xã hội là nền tảng, tiêu biểu cho lợi ích của toàn xã hội. Giai cấp công nhân đại biểu cho lợi ích chung của xã hội. Chỉ có giai cấp công nhân là giai cấp duy nhất không có lợi ích riêng với nghĩa là tư hữu. Nó phấn đấu cho lợi ích chung của toàn xã hội. Nó chỉ tìm thấy lợi ích chân chính của mình khi thực hiện được lợi ích chung của cả xã hội.
	Ở các nước xã hội chủ nghĩa, giai cấp công nhân thông qua quá trình công nghiệp hóa và thực hiện “một kiểu tổ chức xã hội mới về lao động” để tăng năng suất lao động xã hội và thực hiện các nguyên tắc sở hữu, quản lý và phân phối phù hợp với nhu cầu phát triển sản xuất, thực hiện tiến bộ và công bằng xã hội.
	Trên thực tế, hầu hết các nước xã hội chủ nghĩa lại ra đời từ phương thức phát triển rút ngắn, bỏ qua chế độ tư bản chủ nghĩa. Do đó, để thực hiện sứ mệnh lịch sử của mình về nội dung kinh tế, giai cấp công nhân phải đóng vai trò nòng cốt trong quá trình giải phóng lực lượng sản xuất (vốn bị kìm hãm, lạc hậu, chậm phát triển trong quá khứ), thúc đẩy lực lượng sản xuất phát triển để tạo cơ sở cho quan hệ sản xuất mới, xã hội chủ nghĩa ra đời.
	- Nội dung chính trị - xã hội:
	Giai cấp công nhân cùng với nhân dân lao động, dưới sự lãnh đạo của Đảng Cộng sản, tiến hành cách mạng chính trị để lật đổ quyền thống trị của giai cấp thống trị, xóa bỏ chế độ bóc lột, áp bức, giành quyền lực về tay giai cấp công nhân và nhân dân lao động. Thiết lập nhà nước kiểu mới, mang bản chất giai cấp công nhân, xây dựng nền dân chủ xã hội chủ nghĩa, thực hiện quyền lực của nhân dân, quyền dân chủ và làm chủ xã hội của tuyệt đại đa số nhân dân lao động.
	Giai cấp công nhân và nhân dân lao động sử dụng nhà nước của mình, do mình làm chủ như một công cụ có hiệu lực để cải tạo xã hội cũ và tổ chức xây dựng xã hội mới, phát triển kinh tế và văn hóa, xây dựng nền chính trị dân chủ - pháp quyền, quản lý kinh tế - xã hội và tổ chức đời sống xã hội phục vụ quyền và lợi ích của nhân dân lao động, thực hiện dân chủ, công bằng, bình đẳng và tiến bộ xã hội, theo lý tưởng và mục tiêu của chủ nghĩa xã hội.
	- Nội dung văn hóa, tư tưởng:
	Thực hiện sứ mệnh lịch sử của mình, giai cấp công nhân trong tiến trình cách mạng cải tạo xã hội cũ và xây dựng xã hội mới trên lĩnh vực văn hóa, tư tưởng cần phải tập trung xây dựng hệ giá trị mới: lao động; công bằng; dân chủ; bình đẳng và tự do.
	Giai cấp công nhân thực hiện cuộc cách mạng về văn hóa, tư tưởng bao gồm cải tạo cái cũ lỗi thời, lạc hậu, xây dựng cái mới, tiến bộ trong lĩnh vực ý thức tư tưởng, trong tâm lý, lối sống và trong đời sống tinh thần xã hội. Xây dựng và củng cố ý thức hệ tiên tiến của giai cấp công nhân, đó là chủ nghĩa Mác - Lênin, đấu tranh để khắc phục ý thức hệ tư sản và các tàn dư còn sót lại của các hệ tư tưởng cũ. Phát triển văn hóa, xây dựng con người mới xã hội chủ nghĩa, đạo đức và lối sống mới xã hội chủ nghĩa là một trong những nội dung căn bản mà cách mạng xã hội chủ nghĩa trên lĩnh vực văn hóa tư tưởng đặt ra đối với sứ mệnh lịch sử của giai cấp công nhân hiện đại.

3. Những điều kiện quy định và thực hiện sứ mệnh lịch sử của giai cấp công nhân
a) Điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân
	Khẳng định tính tất yếu khách quan sứ mệnh lịch sử của giai cấp công nhân, C. Mác và Ph. Ăngghen đã nêu rõ: “Cùng với sự phát triển của đại công nghiệp, chính cái nền tảng trên đó giai cấp tư sản đã sản xuất và chiếm hữu sản phẩm của nó, đã bị phá sập dưới chân giai cấp tư sản. Trước hết, giai cấp tư sản sản sinh ra những người đào huyệt chôn chính nó. Sự sụp đổ của giai cấp tư sản và thắng lợi của giai cấp vô sản đều là tất yếu như nhau”. Điều kiện khách quan quy định sứ mệnh lịch sử của giai cấp công nhân bao gồm:
	Thứ nhất, do địa vị kinh tế của giai cấp công nhân.
	Giai cấp công nhân là con đẻ, sản phẩm của nền đại công nghiệp, có tính xã hội hóa ngày càng cao, là chủ thể của quá trình sản xuất vật chất hiện đại. Vì thế, giai cấp công nhân đại diện cho phương thức sản xuất tiên tiến và lực lượng sản xuất hiện đại. Do lao động bằng phương thức công nghiệp ngày càng hiện đại, giai cấp công nhân là người sản xuất ra của cải vật chất chủ yếu cho xã hội, làm giàu cho xã hội, có vai trò quyết định sự phát triển của xã hội hiện đại.
	Điều kiện khách quan này là nhân tố kinh tế quy định giai cấp công nhân là lực lượng phá vỡ quan hệ sản xuất tư bản chủ nghĩa, giành chính quyền về tay mình, chuyển từ giai cấp “tự nó” thành giai cấp “vì nó”. Giai cấp công nhân trở thành đại biểu cho sự tiến hóa tất yếu của lịch sử, là lực lượng duy nhất có đủ điều kiện để tổ chức và lãnh đạo xã hội, xây dựng và phát triển lực lượng sản xuất và quan hệ sản xuất xã hội chủ nghĩa, tạo nền tảng vững chắc để xây dựng chủ nghĩa xã hội với tư cách là một chế độ xã hội kiểu mới, không còn chế độ người áp bức, bóc lột người.
	Thứ hai, do địa vị chính trị - xã hội của giai cấp công nhân quy định.
	Là giai cấp sản xuất ra của cải vật chất chủ yếu cho xã hội, nhưng trong chủ nghĩa tư bản giai cấp công nhân không sở hữu tư liệu sản xuất chủ yếu, phải bán sức lao động để kiếm sống, bị bóc lột nặng nề, vì vậy lợi ích cơ bản của họ đối lập trực tiếp với lợi ích cơ bản của giai cấp tư sản và thống nhất với lợi ích cơ bản của đa số nhân dân lao động.
	Là con đẻ của nền sản xuất đại công nghiệp, giai cấp công nhân có những phẩm chất của một giai cấp tiên tiến, giai cấp cách mạng như: tính tổ chức và kỷ luật, tự giác và đoàn kết trong cuộc đấu tranh tự giải phóng mình và giải phóng xã hội. Những phẩm chất ấy của giai cấp công nhân được hình thành từ chính những điều kiện khách quan, được quy định từ địa vị kinh tế và địa vị chính trị - xã hội của nó trong nền sản xuất hiện đại và trong xã hội hiện đại mà giai cấp tư sản và chủ nghĩa tư bản đã tạo ra một cách khách quan, ngoài ý muốn của nó. Giai cấp công nhân được trang bị lý luận tiên tiến là chủ nghĩa Mác - Lênin, có đội tiền phong là Đảng Cộng sản dẫn dắt.
	Tóm lại, sứ mệnh lịch sử của giai cấp công nhân sở dĩ được thực hiện bởi nó là giai cấp cách mạng, đại biểu cho lực lượng sản xuất hiện đại, cho phương thức sản xuất tiên tiến thay thế phương thức sản xuất tư bản chủ nghĩa, xác lập phương thức sản xuất cộng sản chủ nghĩa, hình thái kinh tế - xã hội cộng sản chủ nghĩa. Giai cấp công nhân là giai cấp đại biểu cho tương lai, cho xu thế đi lên của tiến trình phát triển lịch sử - đây là đặc tính quan trọng, quyết định bản chất cách mạng của giai cấp công nhân. Hoàn toàn không phải vì nghèo khổ mà giai cấp công nhân là một giai cấp cách mạng. Tình trạng nghèo khổ của giai cấp công nhân dưới chủ nghĩa tư bản là hậu quả của sự bóc lột, áp bức mà giai cấp tư sản và chủ nghĩa tư bản tạo ra đối với công nhân, đó là trạng thái mà cách mạng sẽ xóa bỏ để giải phóng giai cấp công nhân và giải phóng xã hội.
b) Điều kiện chủ quan để giai cấp công nhân thực hiện sứ mệnh lịch sử
	- Sự phát triển của bản thân giai cấp công nhân cả về số lượng và chất lượng. Thông qua sự phát triển này có thể thấy sự lớn mạnh của giai cấp công nhân cùng với quy mô phát triển của nền sản xuất vật chất hiện đại trên nền tảng của công nghiệp, của kỹ thuật và công nghệ.
	Sự phát triển về số lượng phải gắn liền với sự phát triển về chất lượng của giai cấp công nhân hiện đại, đảm bảo cho giai cấp công nhân thực hiện được sứ mệnh lịch sử của mình. Chất lượng giai cấp công nhân phải thể hiện ở trình độ trưởng thành về ý thức chính trị của một giai cấp cách mạng, tức là tự giác nhận thức được vai trò và trọng trách của giai cấp mình đối với lịch sử, do đó giai cấp công nhân phải được giác ngộ về lý luận khoa học và cách mạng của chủ nghĩa Mác - Lênin.
	Là giai cấp đại diện tiêu biểu cho phương thức sản xuất tiên tiến, chất lượng của giai cấp công nhân còn phải thể hiện ở năng lực và trình độ làm chủ khoa học kỹ thuật và công nghệ hiện đại, nhất là trong điều kiện hiện nay. Để phát triển giai cấp công nhân về số lượng và chất lượng, theo chủ nghĩa Mác - Lênin phải đặc biệt chú ý đến hai biện pháp cơ bản: 1) Phát triển công nghiệp - “tiền đề thực tiễn tuyệt đối cần thiết”; 2) Sự trưởng thành của Đảng Cộng sản - hạt nhân chính trị quan trọng của giai - cấp công nhân.
	Chỉ với sự phát triển về số lượng và chất lượng, đặc biệt về chất lượng, giai cấp công nhân mới có thể thực hiện được sứ mệnh lịch sử của giai cấp mình.
	Đảng Cộng sản là nhân tố chủ quan quan trọng nhất để giai cấp công nhân thực hiện thắng lợi sứ mệnh lịch sử của mình.
	Đảng Cộng sản - đội tiên phong của giai cấp công nhân ra đời và đảm nhận vai trò lãnh đạo cuộc cách mạng là dấu hiệu về sự trưởng thành vượt bậc của giai cấp công nhân với tư cách là giai cấp cách mạng.
	Quy luật chung, phổ biến cho sự ra đời của Đảng Cộng sản là sự kết hợp giữa chủ nghĩa xã hội khoa học, tức chủ nghĩa Mác - Lênin với phong trào công nhân.
	Giai cấp công nhân là cơ sở xã hội và nguồn bổ sung lực lượng quan trọng nhất của Đảng, làm cho Đảng mang bản chất giai cấp công nhân, trở thành đội tiên phong, bộ tham mưu chiến đấu của giai cấp. Đảng Cộng sản đại biểu trung thành cho lợi ích của giai cấp công nhân, của dân tộc và xã hội. Sức mạnh của Đảng không chỉ thể hiện ở bản chất giai cấp công nhân mà còn ở mối liên hệ mật thiết giữa Đảng với nhân dân, với đông đảo quần chúng lao động trong xã hội, thực hiện cuộc cách mạng do Đảng lãnh đạo để giải phóng giai cấp và giải phóng xã hội.
	Ngoài hai điều kiện thuộc về nhân tố chủ quan nêu trên, chủ nghĩa Mác - Lênin còn chỉ rõ: để cuộc cách mạng thực hiện sứ mệnh lịch sử của giai cấp công nhân đi tới thắng lợi, phải có sự liên minh giai cấp giữa giai cấp công nhân với giai cấp nông dân và các tầng lớp lao động khác do giai cấp công nhân thông qua đội tiên phong của nó là Đảng Cộng sản lãnh đạo. Đây cũng là một điều kiện quan trọng không thể thiếu để thực hiện sứ mệnh lịch sử của giai cấp công nhân.

Đây là câu hỏi mà bạn cần trả lời: ${message}
Nếu câu hỏi không liên quan đến tài liệu hoặc nội dung mà bạn cần trả lời thì hãy nói "Câu hỏi của bạn không liên quan đến đề tài của trang web này, bạn có thể tìm hiểu them thông qua các nguồn khác như Google"`;
    const result = await model.generateContent(prompt);
    const text = result.response.text(); // <-- get actual reply text

    res.json({ text });
  } catch (error) {
    console.error(error);
    res.status(500).json({ message: "Failed to get response" });
  }
};
